export const mockUser = {
  login: 'ddevtk',
  id: 67871183,
  node_id: 'MDQ6VXNlcjY3ODcxMTgz',
  avatar_url: 'https://avatars.githubusercontent.com/u/67871183?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/ddevtk',
  html_url: 'https://github.com/ddevtk',
  followers_url: 'https://api.github.com/users/ddevtk/followers',
  following_url: 'https://api.github.com/users/ddevtk/following{/other_user}',
  gists_url: 'https://api.github.com/users/ddevtk/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/ddevtk/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/ddevtk/subscriptions',
  organizations_url: 'https://api.github.com/users/ddevtk/orgs',
  repos_url: 'https://api.github.com/users/ddevtk/repos',
  events_url: 'https://api.github.com/users/ddevtk/events{/privacy}',
  received_events_url: 'https://api.github.com/users/ddevtk/received_events',
  type: 'User',
  site_admin: false,
  name: 'Bui Duc Duong',
  company: null,
  blog: '',
  location: 'Ha Noi',
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 15,
  public_gists: 0,
  followers: 0,
  following: 6,
  created_at: '2020-07-05T16:38:22Z',
  updated_at: '2021-07-01T21:52:36Z',
};
